name: MULTI-STAGE-CICD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo 'validating the project'
  dev:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a dev environment
        run: echo 'deploying dev environment'
  qa:
    needs: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a qa envirnment
        run: echo 'deploying qa environment'
  prod:
    needs: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a prod environment
        run: echo 'deploying prod environment'
